### ISSUE TITLE
ASAR packaging breaks this module

### ISSUE THREAD

**Issue by Unforgiven-wanda** [rhysd/electron-about-window#10]
Hello,
Although running in dev runs well, when packaging this app through electron-builder into an ASAR archive, this module breaks completely. Trying to require `about.html` in the wrong folder.
Thank you.

**Comment by rhysd** [comment]
I tried following but it works.

```console
$ git clone https://github.com/rhysd/electron-about-window
$ cd example
$ npm install electron-about-window
$ vim main.js # Replace require('..') with require('electron-about-window')
$ cd ..
$ asar pack example example.asar
$ electron example.asar # it works for me
```

Please provide more information (i.e. expected about.html path and actual about.html path, etc)

**Comment by Unforgiven-wanda** [comment]
Hello again,
Running on Ubuntu Zesty (17.04), Electron 1.7.8, x64.

I am using this module inside a project based on https://github.com/chentsulin/electron-react-boilerplate/
Debugging the production build, this is the error that I get:
`file:///home/user/Folder/ols-immo/release/linux-unpacked/resources/about.html`

I am suspecting electron-builder.

**Comment by rhysd** [comment]
I don't know why the `about.html` is not in `node_modules/electron-about-window`. I think someone moved the HTML file. Generally, installed npm packages would be put at `resources/app/node_modules/{package}`.

The code is at https://github.com/rhysd/electron-about-window/blob/master/src/index.ts#L83.

I guess `__dirname` is unexpected in app. Could you try out below?

1. Open about.html in your node_modules/electron-about-window
2. Insert `console.log(__dirname)` to just before the above line
3. Make a package
4. Run app and watch console in DevTools

What is displayed?

**Comment by Unforgiven-wanda** [comment]
I added `console.log` to `src/index.js` and `src/index.ts` but nothing is printed.
I even added a `console.log`after the `openDevTools` statement. That's rather strange.
(And yes I'm checking the devTools window of the about window)

**Comment by rhysd** [comment]
Um, did you rebuild the package after modifying code? I don't know what electron-react-boilerplate but it may transpile/bundle source and original source code.

**Comment by Unforgiven-wanda** [comment]
@rhysd Yes, I believe it does bundle the original source code through Webpack.
I'm going to fork this repo, modify it and install it from here. I'll let you know.

**Comment by anthonyraymond** [comment]
Electron-react-boilerplate has a dual package structure, even if i don't completly understand why, adding `about-window` to `app/package.json` instead of `package.json` works.

However i was not able to set the icon correcly yet.

**Comment by Unforgiven-wanda** [comment]
Ah, thank you. Haven't had the time to address this issue. I'll test it as soon as I can and close the issue if it works.

**Comment by rhysd** [comment]
@anthonyraymond Thank you for your help!

**Comment by neilning-xc** [comment]
> **Fix packaging** Electron-react-boilerplate has a dual package structure, even if i don't completly understand why, adding `about-window` to `app/package.json` instead of root `package.json` works.
> 
> **Include image properly** Create the folder `app/images` and add your image in it (the name of my image will be `about-icon.png`).
> 
> In the **root** `package.json` find the `file` property and add `images/about-icon.png` to it
> 
> ```
> "files": [
>      "dist/",
>      "node_modules/",
>      "app.html",
>      "main.prod.js",
>      "main.prod.js.map",
>      "package.json",
>      "images/about-icon.png"
>    ]
> ```
> 
> Then on your code use the path as follow:
> 
> ```
> aboutWindow({
>   icon_path: path.join(__dirname, 'images/about-icon.png'),
>   package_json_dir: __dirname
> });
> ```

This fix my issue, great work!
