### ISSUE TITLE
Request feature: Use our own html file

### ISSUE THREAD

**Issue by anthonyraymond** [rhysd/electron-about-window#12]
Hi @rhysd, thanks for this nice project :)

I was wondering if you could pimp a little bit this proejct to allow usage of our own .html file?

And also add a empty div where we could put some inline html with:
```
aboutWindow({
      icon_path: path.join(__dirname, 'images/about-icon.png'),
      package_json_dir: __dirname,
      customDiv: '<p><b>This</b> is a dynamic content</p>
    });
```

**Comment by rhysd** [comment]
If you want to customize contents, please use `use_inner_html` option.
