### ISSUE TITLE
Cannot load local resource

### ISSUE THREAD

**Issue by hacker112** [rhysd/electron-about-window#16]
I get the following:
Not allowed to load local resource: file://node_modules/about-window/about.html

Might it be that it it is not compatible with electron-webpack?
I am using electron-version 1.7.10

**Comment by rhysd** [comment]
I'm not electron-webpack user, so I'm not sure this package can work with it. 

> Not allowed to load local resource: file://node_modules/about-window/about.html

When and who outputs the error message? The `file://` protocol requires absolute path. But `file://node_modules/about-window/about.html` looks to utilize relative path. It should be `file:///path/to/node_modules/about-window/about.html` in the case, I guess.

**Comment by hacker112** [comment]
I get the message `Not allowed to load local resource: file://node_modules/about-window/about.html` in the dev tools console if when I enable the tools for the about window.

I think it would be possible to make it work with both with and without webpack.

**Comment by rhysd** [comment]
Thanks for the info. What I want to clarify is that the root cuse of the error message is actually webpack. But I'm not a webpack user and don't know how to use it.

**Comment by alxmiron** [comment]
I think the error is because of 
```
const index_html = 'file://' + path.join(__dirname, '..', 'about.html');
```

After webpack build `__dirname` will point to output folder, but `about.html` will be left in node_modules. Need to pass `about_page_dir` option, same as `package_json_dir ` to fix this

**Comment by hacker112** [comment]
I tried to use this package again and version 1.11.0 seems to work fine with electron-webpack 1.13.0. So for me this is not an issue anymore 👍 Thanks for a great package!
