### ISSUE TITLE
Question: is it possible to not show electron/chrome/node/v8 info

### ISSUE THREAD

**Issue by odiseo42** [rhysd/electron-about-window#24]
Looks unnecessary for my case and I'd like to hide it.

**Comment by jremi** [comment]
@odiseo42 , i had to hide this on my project ... here is how you can do this...

For example:

Create a file in the root of your electron project : **about-window.css**

You can add this to the css file:

`.versions {
   display : none;
}`

Then inside your electron project where you initiate the electron-about-window add the **css_path** option.

It should look like this example:

`openAboutWindow({
    icon_path: path.join(__dirname, 'awesome-logo.png'),
    description: 'App makes you awesome',
    homepage: 'http://www.awesome.com',
    copyright: 'Copyright (c) 2018 Awesome Inc',
    product_name: 'Awesome App',
    css_path:[path.join(__dirname,'about-window.css')]
  })`

**Comment by alexanderturinske** [comment]
Actually, I wonder why this isn't something one can toggle with an option in the code.
