### ISSUE TITLE
Issue with TypeScript 2.9

### ISSUE THREAD

**Issue by mrdziuban** [rhysd/electron-about-window#27]
When trying to call `openAboutWindow` in an app using TypeScript 2.9, I get this error:

```
TS2349: Cannot invoke an expression whose type lacks a call signature.
Type 'typeof import("/path/to/node_modules/about-window/src/index")'
has no compatible call signatures.
```

It seems like the TypeScript compiler is looking at `index.ts` instead of the type declarations in `index.d.ts`?

**Comment by rhysd** [comment]
Could you show the code snippet which utilizes this library's API)? I guess a compiler raises an error  where `openAboutWindow` is called, am I correct?

**Comment by rhysd** [comment]
I found some problem with TypeScript 2.9. Though the reported compilation error is different from yours. Could you update package version to v1.11.1 and try it?

**Comment by mrdziuban** [comment]
Thanks @rhysd, v1.11.1 does fix my issue. And yes, the error was raised when calling `openAboutWindow`.
