### ISSUE TITLE
Add support for renderer process

### ISSUE THREAD

**Issue by ayltai** [rhysd/electron-about-window#3]
The current implement of `openAboutWindow` supports calling it from the main process only. Please consider adding support for calling it from a renderer process.

**Comment by rhysd** [comment]
Did you try `remote.require`? I guess below works.

```javascript
const remote = require('electron').remote;
const openAboutWindow = remote.require('about-window').default;

openAboutWindow({
    icon_path: 'path/to/icon.png'
});
```

**Comment by ayltai** [comment]
Yes it works. Thanks for helping!
