### ISSUE TITLE
win_title doesn't work.

### ISSUE THREAD

**Issue by Brouilles** [rhysd/electron-about-window#43]
Hi, 
Thanks for this project. I have a problem, the string set with the parameter win_title doesn't work. The window conserve the default name `About {app name}`.

Electron: 6.0.6
Node: 12.4.0

Any idea to fix this?
Thanks.

**Comment by Brouilles** [comment]
I use
```
win_options: {
    title: 'À propos'
},
```
Because `win_title` don't work.
Thanks.

**Comment by rhysd** [comment]
You're correct. `win_title` does not exist actually. It was my bad that README.md was not correct.
