### ISSUE TITLE
I set open_devtools: false, but the devtools window will still open.

### ISSUE THREAD

**Issue by zwdgit** [rhysd/electron-about-window#47]

**Comment by rhysd** [comment]
Please provide what you did for reproduction. Otherwise I can say nothing

**Comment by rhysd** [comment]
https://github.com/rhysd/electron-about-window/blob/master/src/index.ts#L157 At least implementation guards opening devtools by checking the prop.

**Comment by rhysd** [comment]
Closing as no response.
