### ISSUE TITLE
getName is deprecated in Electron 7

### ISSUE THREAD

**Issue by dtslvr** [rhysd/electron-about-window#48]
I get the following warninig when starting the _about window_ with Electron 7:

```
'getName function' is deprecated and will be removed. Please use 'name property' instead.
```

See here: https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname

**Comment by rhysd** [comment]
This was fixed by #50.

**Comment by dtslvr** [comment]
When do you plan the next release?

**Comment by rhysd** [comment]
I'm sorry for the lag. I'll publish new version tonight (JST).
