### ISSUE TITLE
Setting about-window with electronforge and its webpack plugin

### ISSUE THREAD

**Issue by loctran016** [rhysd/electron-about-window#67]
Hi, there. Thanks for creating such a good package. I've run to problem while trying to make this work in my project (I'm using electron-forge and its webpack plugin)
My repo can be found on [Github](https://github.com/cokaps016/GenZOC)
My config files for about-window is [here](https://github.com/cokaps016/GenZOC/blob/main/src/main/menu.js#L100-L118)
Here is my problem:

![image](https://user-images.githubusercontent.com/64778285/122574687-1ca38c80-d07a-11eb-92ae-94ca24f026b4.png)
![image](https://user-images.githubusercontent.com/64778285/122574725-2927e500-d07a-11eb-8b3e-e8e63e96638c.png)

**Comment by maximborisov** [comment]
I have the same problem

**Comment by dtslvr** [comment]
I have the same problem after upgrading `electron` from version `12.0.5` to `14.0.1`.

**Comment by nosferatu500** [comment]
you can try to use my fork:
```yarn add @nosferatu500/about-window```

```npm  install @nosferatu500/about-window```

Based on Electron 14

**Comment by dtslvr** [comment]
Seems to be fixed for me via https://github.com/rhysd/electron-about-window/releases/tag/v1.15.0 👍🏻

**Comment by rhysd** [comment]
Thank you for confirming that. Closing.
