### ISSUE TITLE
Unable to set icon in title bar of the about window.

### ISSUE THREAD

**Issue by dcvice1967** [rhysd/electron-about-window#7]
Is it possible to set the icon in the top left of the about window as you can for a browser window created directly?

**Comment by rhysd** [comment]
Currently icon is not set to window frame as you pointed. With current API, we need to specify `icon` to `win_options` object. But I think the `icon_path` value should also be set to window frame icon. I'll update this library.

**Comment by rhysd** [comment]
I published v1.6.2. Please try it.
