### ISSUE TITLE
Not showing the icon

### ISSUE THREAD

**Issue by Rawnly** [rhysd/electron-about-window#8]
Same issue also with the example given..

![screen shot 2017-06-14 at 14 58 29](https://user-images.githubusercontent.com/16429579/27133328-03c4be5a-5112-11e7-8eb8-7fb4500c73e1.png)

**Comment by rhysd** [comment]
Of course I confirmed example worked. It's not broken in my environment. Did you `npm install && npm build` after `git pull`?

![2017-06-14 22 56 31](https://user-images.githubusercontent.com/823277/27135928-c9448e16-5154-11e7-9441-9ae26ed15c31.png)

**Comment by rhysd** [comment]
Latest Electron may cause this problem. I'm going to investigate this.

**Comment by rhysd** [comment]
It seems that  TypeScript causes this problem. Recent TypeScript inserts below line.

```js
Object.defineProperty(exports, "__esModule", { value: true });
```

But `exports` is not defined in Electron environment.

**Comment by dcvice1967** [comment]
Thanks for looking into it.

**Comment by rhysd** [comment]
The problem was reported as below link

https://github.com/electron/electron/issues/2863

I fixed this in a9a308. Thank you for catching this.
