### ISSUE TITLE
Typescript error with BrowserWindowOptions

### ISSUE THREAD

**Issue by kcampion** [rhysd/electron-about-window#9]
When Webpack tries to build my app, this mistake appears:
```
ts-loader: Using typescript@2.3.4 and /Users/me/Myapp/app/node_modules/about-window/src/tsconfig.json

Error: ./app/~/about-window/src/lib.d.ts
(26,28): error TS2694: Namespace 'Electron' has no exported member 'BrowserWindowOptions'.
```

- Electron version: 1.6.10
- Operating system: macOs 10.12.5

**Comment by rhysd** [comment]
It's because 'electron' package now contains official electron.d.ts. TypeScript compiler refers it. Type definitions of electron-about-window assumed old electron.d.ts in DefinitelyTyped.

Now I updated type definitions and published v1.7.0. Please try it.

**Comment by kcampion** [comment]
The error has disappeared indeed, but I've another one:
```
WARNING in ./app/~/about-window/src/index.js
Critical dependencies:
9:15-32 the request of a dependency is an expression
 @ ./app/~/about-window/src/index.js 9:15-32

WARNING in ./app/~/about-window/src/index.js.map
Module parse failed: /Users/me/Myapp/app/node_modules/about-window/src/index.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
```

**Comment by rhysd** [comment]
I didn't see the warning. It looks to come from not a TypeScript compiler, but a webpack's bundler. I'm not a webpack user and I don't know it should be fixed or how to fix...

**Comment by kcampion** [comment]
Ok, don't worry, thank you for your help about the first issue.

**Comment by rhysd** [comment]
If you find the warning derives from this package, feel free to create a new issue with the details :smile:
